CREATE SCHEMA IF NOT EXISTS app;
CREATE SCHEMA IF NOT EXISTS analytics;
CREATE SCHEMA IF NOT EXISTS lookup;

CREATE TABLE IF NOT EXISTS app.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    password_hash TEXT,
    name TEXT,
    google_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verification_code TEXT,
    plan TEXT NOT NULL DEFAULT 'free',
    api_key TEXT,
    api_requests_count INTEGER NOT NULL DEFAULT 0,
    last_api_usage_date DATE,
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_api_key_unique UNIQUE (api_key)
);

CREATE TABLE IF NOT EXISTS app.projects (
    id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS app.api_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    project_id TEXT NOT NULL REFERENCES app.projects(id) ON DELETE CASCADE,
    name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS app.licenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app.users(id) ON DELETE CASCADE,
    license_key TEXT NOT NULL UNIQUE,
    plan_type TEXT NOT NULL DEFAULT 'annual_db',
    status TEXT NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ,
    last_downloaded_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS analytics.analytics_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    hashed_ip TEXT NOT NULL,
    country_code TEXT,
    country_name TEXT,
    city TEXT,
    region TEXT,
    asn TEXT,
    asn_name TEXT,
    netname TEXT,
    is_datacenter BOOLEAN NOT NULL DEFAULT FALSE,
    is_vpn BOOLEAN NOT NULL DEFAULT FALSE,
    user_type TEXT,
    path TEXT,
    method TEXT,
    status_code INTEGER,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS analytics.analytics_aggregates_hourly (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    hour TIMESTAMPTZ NOT NULL,
    country_code TEXT,
    asn TEXT,
    is_datacenter BOOLEAN,
    is_vpn BOOLEAN,
    request_count INTEGER NOT NULL DEFAULT 0,
    unique_ip_estimate INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT analytics_aggregates_hourly_unique
        UNIQUE (project_id, hour, country_code, asn, is_datacenter, is_vpn)
);

CREATE TABLE IF NOT EXISTS analytics.analytics_aggregates_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id TEXT NOT NULL,
    date DATE NOT NULL,
    country_code TEXT,
    asn TEXT,
    netname TEXT,
    request_count INTEGER NOT NULL DEFAULT 0,
    unique_ip_estimate INTEGER NOT NULL DEFAULT 0,
    vpn_count INTEGER NOT NULL DEFAULT 0,
    datacenter_count INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT analytics_aggregates_daily_unique
        UNIQUE (project_id, date, country_code, asn)
);

CREATE TABLE IF NOT EXISTS lookup.city_layer (
    network TEXT,
    continent_code TEXT,
    continent_name TEXT,
    country_iso_code TEXT,
    country_name TEXT,
    subdivision_1_iso_code TEXT,
    subdivision_1_name TEXT,
    city_name TEXT,
    metro_code INTEGER,
    time_zone TEXT,
    postal_code TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    accuracy_radius INTEGER,
    start_ip CHAR(32),
    end_ip CHAR(32),
    is_multicast BOOLEAN DEFAULT FALSE,
    is_fallback BOOLEAN DEFAULT FALSE,
    is_crawler BOOLEAN DEFAULT FALSE,
    netname TEXT,
    org TEXT,
    asn TEXT,
    source TEXT,
    utc_offset TEXT,
    zip_code TEXT
);

CREATE TABLE IF NOT EXISTS lookup.threat_level (
    start_ip CHAR(32),
    end_ip CHAR(32),
    threat_level TEXT
);

CREATE TABLE IF NOT EXISTS lookup.asn_lookup (
    start_ip CHAR(32),
    end_ip CHAR(32),
    asn TEXT,
    name TEXT,
    org TEXT,
    domain TEXT,
    country_code TEXT
);

CREATE TABLE IF NOT EXISTS lookup.countries (
    alpha2 TEXT PRIMARY KEY,
    alpha3 TEXT,
    numeric INTEGER,
    name_short TEXT,
    name_long TEXT
);

CREATE TABLE IF NOT EXISTS lookup.country_currency (
    country_code TEXT PRIMARY KEY,
    country_name TEXT,
    currency_name TEXT,
    currency_code TEXT
);

CREATE TABLE IF NOT EXISTS lookup.country_dial (
    country_code TEXT PRIMARY KEY,
    dial_code TEXT
);

CREATE TABLE IF NOT EXISTS lookup.crawler_ranges (
    start_ip CHAR(32) PRIMARY KEY,
    end_ip CHAR(32),
    bot_name TEXT,
    cidr TEXT
);

CREATE TABLE IF NOT EXISTS lookup.elevation_lookup (
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    elevation DOUBLE PRECISION,
    PRIMARY KEY (latitude, longitude)
);

CREATE TABLE IF NOT EXISTS lookup.fallback_city (
    country_code TEXT PRIMARY KEY,
    capital_city TEXT
);

CREATE TABLE IF NOT EXISTS lookup.ip_ranges (
    start_ip BIGINT NOT NULL,
    end_ip BIGINT NOT NULL,
    country TEXT,
    netname TEXT,
    org TEXT,
    source TEXT,
    is_vpn BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS lookup.iptwo_new (
    ip_from BIGINT,
    ip_to BIGINT,
    country_code TEXT,
    country_name TEXT,
    region TEXT,
    city TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    zipcode TEXT,
    utc_offset TEXT,
    start_ip CHAR(32),
    end_ip CHAR(32)
);

CREATE TABLE IF NOT EXISTS lookup.user_type (
    start_ip CHAR(32),
    end_ip CHAR(32),
    ip_type TEXT
);

CREATE TABLE IF NOT EXISTS lookup.vpn_overrides (
    ip CHAR(32) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS lookup.vpn_ranges (
    start_ip CHAR(32),
    end_ip CHAR(32),
    PRIMARY KEY (start_ip, end_ip)
);
